---
# tasks file for nginx
- name: Assertions
  assert:
    that:
    - ansible_os_family in aliases_file
    - ansible_os_family in nginx_user

- name: Check if dhparams file exists
  stat:
    path: /etc/ssl/dhparams.pem
  register: stat_dhparams

- name: APT install
  when: ansible_pkg_mgr == 'apt'
  apt:
    name: nginx-full
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: pkg install
  when: ansible_pkg_mgr == 'openbsd_pkg'
  openbsd_pkg:
    name: nginx%1
    state: present

- name: Alias emails to root
  when: nginx_mail_alias is defined
  lineinfile:
      dest: '{{ aliases_file[ansible_os_family] }}'
      create: yes
      line: '{{ nginx_user[ansible_os_family] }}: {{ nginx_mail_alias }}'
      regexp: '{{ nginx_user[ansible_os_family] }}:'
  notify:
      - Update SMTPd database

- name: Get Nginx version
  nginx_facts:

- name: Remove default error log directive
  when: nginx_error_log is defined
  lineinfile:
      regexp: error_log
      dest: /etc/nginx/nginx.conf
      state: absent

- name: Create configuration directories
  with_items:
  - /etc/nginx/sites-enabled
  - /etc/nginx/conf.d
  file:
    path: '{{ item }}'
    owner: root
    group: 0
    mode: 0o0755
    state: directory

- name: Include configuration directories
  with_items:
  - line: include /etc/nginx/sites-enabled/*;
    regexp: /etc/nginx/sites-enabled
  - line: include /etc/nginx/conf.d/*.conf;
    regexp: /etc/nginx/conf.d
  lineinfile:
    dest: /etc/nginx/nginx.conf
    line: '{{ item.line }}'
    insertafter: 'http {'
    regexp: '{{ item.regexp|default(omit) }}'
    state: present
  notify:
  - Reload Nginx

- name: Disable default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
  - Reload Nginx

- name: Copy virtualhosts templates
  with_fileglob:
  - '{{ role_path }}/templates/nginx/sites-enabled/*'
  - '{{ playbook_dir }}/templates/nginx/sites-enabled/*'
  template:
      src: '{{ item }}'
      dest: '/etc/nginx/sites-enabled/{{ item|basename }}'
      owner: root
      group: 0
      mode: 0o0644
  notify:
  - Reload Nginx

- name: Copy config templates
  with_fileglob:
  - '{{ role_path }}/templates/nginx/conf.d/*.conf'
  - '{{ playbook_dir }}/templates/nginx/conf.d/*.conf'
  template:
      src: '{{ item }}'
      dest: '/etc/nginx/conf.d/{{ item|basename }}'
      owner: root
      group: 0
      mode: 0o0644
  notify:
  - Reload Nginx

- name: Validate config
  command: nginx -t
  changed_when: False

- name: Enable service
  service:
      name: nginx
      state: started
      enabled: yes

- meta: flush_handlers

- name: Wait for Nginx to recieve requests
  wait_for:
      port: 80
