---
# tasks file for ansible-role-nginx

- assert:
    that:
    - ansible_os_family in [ 'Debian', 'OpenBSD' ]

- name: APT install
  when: ansible_pkg_mgr == 'apt'
  apt:
    name: nginx-full
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: pkg install
  when: ansible_pkg_mgr == 'openbsd_pkg'
  openbsd_pkg:
    name: '{{ nginx_openbsd_pkg[ansible_distribution_release] }}'
    state: present

- name: Create configuration directories
  with_items:
  - /etc/nginx/sites-enabled
  - /etc/nginx/conf.d
  file:
    path: '{{ item }}'
    owner: root
    group: 0
    mode: 0o0755
    state: directory

- name: Configure
  with_items:
  - line: include /etc/nginx/sites-enabled/*;
  - line: include /etc/nginx/conf.d/*.conf;
  - line: access_log syslog:localhost;
    regexp: access_log
  - line: error_log syslog:locahost;
    regexp: error_log
  lineinfile:
    dest: /etc/nginx/nginx.conf
    line: '{{ item.line }}'
    insertafter: 'http {'
    regexp: '{{ item.regexp|default(omit) }}'
    state: present
  notify:
  - Reload Nginx

- name: Disable default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
  - Reload Nginx

- name: Copy templates
  with_fileglob:
  - templates/nginx/sites-enabled/*
  - templates/nginx/conf.d/*.conf
  template:
      src: '{{ item }}'
      dest: '/etc/{{ item }}'
      owner: root
      group: 0
      mode: 0o0644
  notify:
  - Reload Nginx

- name: Alias emails to root
  lineinfile:
      dest: '{{ aliases_file[ansible_os_family] }}'
      create: yes
      line: 'nginx: root'
      regexp: 'nginx:'
  notify:
      - Update SMTPd database

- name: Enable service
  service:
      name: nginx
      state: running
      enabled: yes

- wait_for:
    port: 80
